pipeline {
  agent any
  
  stages {	
	  
	stage('Maven Compile'){
		steps{
			echo 'Project compile stage'
			bat label: 'Compilation running',
			script: '''cd another-maven-project
			mvn compile'''
	       	}
	}
	
	stage('Unit Test') {
	   steps {
			echo 'Project Testing stage'
			bat label: 'Test running',
			script: '''cd another-maven-project
			mvn test'''
	       
       		}
   	}

	stage('Jacoco Coverage Report') {
        	steps{
            		jacoco()
		}
	}
       
       stage('SonarQube'){
		steps{
				bat label: '',
				script: '''cd another-maven-project
				mvn sonar:sonar \
				-Dsonar.host.url=http://localhost:9000 \
				-Dsonar.login=305ed8e903ac731c6f15efd07855b351073f05a1'''
			}
   		}
	
	stage('Maven Package'){
		steps{
			echo 'Project packaging stage'
			bat label: 'Project packaging',
			script: '''cd another-maven-project
			mvn package'''
		}
	} 		
    
  }
}
